---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubberduck-world
  namespace: minikube-demo
  labels:
    app: rubberduck
    env: staging
spec:
  replicas: 10
  selector:
    matchLabels:
      app: rubberduck
  template:
    metadata:
      labels:
        app: rubberduck
        tier: api
        env: staging
    spec:
      containers:
      - name: calert
        image: mrkaran/rubberduck:1.0.1
        ports:
        - containerPort: 8080