---
apiVersion: v1
kind: Service
metadata:
  name: rubberduck-service
  namespace: minikube-demo
  labels:
    app: expose-rubberduck-app
spec:
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: rubberduck
  type: NodePort