---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: minikube-demo
  labels:
    app: expose-hello-app
spec:
  ports:
  - protocol: TCP
    port: 6000
  selector:
    app: hello
  type: NodePort